### ISSUE TITLE
VSCode prompts non-sense.

### ISSUE THREAD

**Issue by Magicloud** [mads-hartmann/bash-language-server#83] opened 2018-10-08 04:17 UTC
I am using Bash IDE extension in VSCode. And installed bash-language-server as descripted in its details.

Now I have two problems. One is apparently something is wrong. The other is "I am not sure".

1. Code prompt are all non-sense. For example, I typed "then", I got "thinkjettopbm". I typed "case", I got "catchsegv".

2. Code completion does not work. In my idea, this is something like, when I typed "case", it would insert the "esac". But in my IDE, it does not. Just marks a bunch of lines "syntax error" red underlines.

What should I do?

**Comment by rcjsuen** [comment] 2018-10-08 08:17
@Magicloud I highly suggest you provide some screenshots and/or a short video (or animated gif) of the behaviour you are seeing.

**Comment by skovhus** [comment] 2018-10-08 08:50
> Code prompt are all non-sense. For example, I typed "then", I got "thinkjettopbm". I typed "case", I got "catchsegv".

Code suggestions are based on executables on our path. That means that `thinkjettopbm` is a valid command in a shell script. Would be nice with more context-aware suggestions though. PRs and suggestions are more than welcome. :)

**Comment by Magicloud** [comment] 2018-10-08 15:01
Following pics show both problems. Sorry, I could get GIF recorder (peak) to work with my desktop.

![1539010635](https://user-images.githubusercontent.com/1886157/46616815-f188e100-cb4d-11e8-9d47-e4066b9cddaf.png)
![1539010678](https://user-images.githubusercontent.com/1886157/46616816-f2217780-cb4d-11e8-9dee-d980f06cbfc3.png)
![1539010704](https://user-images.githubusercontent.com/1886157/46616818-f2217780-cb4d-11e8-8b8d-4c6b6c5911ec.png)
![1539010721](https://user-images.githubusercontent.com/1886157/46616819-f2217780-cb4d-11e8-85a9-775b863b0b52.png)
![1539010739](https://user-images.githubusercontent.com/1886157/46616821-f2ba0e00-cb4d-11e8-8f04-cac7ef599eac.png)
![1539010766](https://user-images.githubusercontent.com/1886157/46616822-f2ba0e00-cb4d-11e8-8f8f-d97e25e3090d.png)

**Comment by thomasjm** [comment] 2018-10-15 08:16
Looking at the server code it seems that `bash-language-server` always appends *all* executables it can find to the autocomplete results, and then leaves it up to the client (VSCode or other IDE) to do its best to filter them (!).

https://github.com/mads-hartmann/bash-language-server/blob/ba43db6e5b6a2f755d04e4ce97193b9849720458/server/src/server.ts#L187

I think that's why you're seeing these results.

From what I've seen of other language servers, `bash-language-server` should be doing more work here...I would hope it could use its understanding of bash grammar to a) identify places where executable commands should actually appear, and b) filter them based on the token that has been typed so far at that point.

**Comment by thomasjm** [comment] 2019-04-06 12:45
@skovhus any chance this could be a high priority fix? I think it's more of a serious bug than an enhancement. 

I just dug into this in more detail in Atom. When I type something like `ech` (expecting to see completions like `echo`), `bash-language-server` returns almost 3,500 results, almost all of which are nonsensical. The only reason completion works reasonably at all on Atom is because Atom itself is smart enough to prune the results before showing the autocomplete popup.

For other clients that don't filter the results by default, this makes `bash-language-server` completion almost unusable.

FWIW, I think it would be simple to compare the executable strings against the token where the cursor is found before returning the list. Thanks!

**Comment by skovhus** [comment] 2019-04-06 14:10
Agree. 👍 Contributions are more than welcome.

**Comment by skovhus** [comment] 2019-12-13 10:34
@thomasjm is this still a problem?

**Comment by yangyingchao** [comment] 2019-12-27 02:16
I'm using the latest release of bash-language-server with emacs, and I can reproduce this issue. Really annoying... It would be great to have thomsjm's pull request merged...

thanks

**Comment by thomasjm** [comment] 2019-12-27 02:34
I've not found time yet to write tests for the PR -- any help pushing it over the finish line would be welcome :)

**Comment by skovhus** [comment] 2020-03-04 12:48
Several fixes for this was released as `bash-language-server@1.10.0` and the VS Code client version 1.7.0.

@Magicloud @yangyingchao please let us know if this works for you. And thanks for reporting these issues.

**Closed by skovhus** 2020-03-04 12:48 UTC
Labels: enhancement, help wanted

**Comment by yangyingchao** [comment] 2020-05-12 03:31
![Screen Shot 2020-05-12 at 11 29 35 AM](https://user-images.githubusercontent.com/990329/81635496-f0174d00-9443-11ea-9297-6293bcc4bb81.png)

No push, but still seems wrong in Emacs...

**Comment by yangyingchao** [comment] 2020-05-12 03:33
![Screen Shot 2020-05-12 at 11 32 23 AM](https://user-images.githubusercontent.com/990329/81635657-471d2200-9444-11ea-86f6-9f3235ebb2b7.png)

Still not resolved when using emacs + lisp-mode ...

**Comment by skovhus** [comment] 2020-05-12 06:03
@yangyingchao which OS? And which version of bash language server are you running?

**Comment by yangyingchao** [comment] 2020-05-12 06:15
I tested both Mac OS 10.13.6 and RHEL 7.3, with bash-language-server 1.14.0. 

Thanks.
