### ISSUE TITLE
Extension shows error on hovering

### ISSUE THREAD

**Issue by anishmittal2020** [mads-hartmann/bash-language-server#80] opened 2018-09-23 20:47 UTC
```
Hovering over 21:22
[Error - 10:43:37 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Error: connect ECONNREFUSED 127.0.0.1:5000
  Code: -32603 
```

What should I do?

**Comment by skovhus** [comment] 2018-09-24 06:30
Can you send us the file where this happened or a small reproducible snippet?

Please also include OS version and bash language server version. 

Thanks.

**Comment by sandinmyjoints** [comment] 2018-10-01 15:51
I am seeing this too. 
- bash-language-server@1.5.2
- macOS 10.12.6

Seems to happen with any file, for example:

```bash
ls
```

Happens when I hover over `ls`.

**Comment by sandinmyjoints** [comment] 2018-10-01 15:53
Actually, I get a slightly different error message than the OP: `Request textDocument/hover failed with message: undefined is not a valid argument for URI (Internal Error)`

**Comment by skovhus** [comment] 2018-10-01 20:54
@anishmittal2020 I'm wondering why it calls `127.0.0.1:5000`. Did you set up `bashIde.explainshellEndpoint` as explained in the README?

**Comment by skovhus** [comment] 2018-10-01 20:55
@sandinmyjoints

> Actually, I get a slightly different error message than the OP: Request textDocument/hover failed with message: undefined is not a valid argument for URI (Internal Error)

Unfortunately I can't reproduce. Can you upload a screenshot of your entire editor and this error showing?

**Comment by sandinmyjoints** [comment] 2018-10-01 23:03
[screenshot](https://cldup.com/uhDB1E7i7m1/3pd8kG.png)

This is Emacs 26.1 using https://github.com/emacs-lsp/lsp-sh

**Comment by mattiasb** [comment] 2018-10-04 20:17
I get the same error. My guess is that error is [here](https://github.com/mads-hartmann/bash-language-server/blob/master/server/src/server.ts#L112). You should probably check for `undefined` as well.

**Comment by skovhus** [comment] 2018-10-05 05:19
> I get the same error. My guess is that error is here. 

I think you are right. Good catch!

**Comment by mattiasb** [comment] 2018-10-05 08:07
> > I get the same error. My guess is that error is here.
> 
> I think you are right. Good catch!

I'm always right! *humble brags* 😂 😉

**Comment by skovhus** [comment] 2018-10-05 08:34
Let me know if you want to create a PR. :)

**Comment by mattiasb** [comment] 2018-10-05 10:40
> Let me know if you want to create a PR. :)

tbh I don't even know how to make an undefined-check in Typescript. It's not a language I have on my bucket-list so to speak. :P

**Comment by skovhus** [comment] 2018-10-07 14:35
Should be fixed in 1.5.4. Please try to upgrade by running a `npm install -g bash-language-server`

**Comment by skovhus** [comment] 2018-10-07 14:36
Let me know if it works for you guys. :) @anishmittal2020 @mattiasb

**Closed by skovhus** 2018-10-07 14:35 UTC
Labels: question

**Comment by mattiasb** [comment] 2018-10-07 23:58
Works like a charm, thanks! :)
